function Main()
{
	run VariableSetup();
	run StartCounter();
}

function VariableSetup()
{
	int: ADD       = 1;
	int: MAX_COUNT = 100;
	int: Counter   = 0;
}

function StartCounter()
{
	Console.out.warning("Starting counter!");
	run Count();
}

function Count()	
{
	Counter += ADD;
	if (MAX_COUNT > Counter) -> Count() : End();
}

function End()
{
	Console.out.warning(Counter)
	Console.out.error("End of application -- PROGRAM!");
}